name: Generate S3 Presigned URLs

# Triggers the workflow on releases published with tag pattern s3.url.*, e.g. s3.url.0.0.1
on:  
  release:
    types: [published]

jobs:
  release:
    if: contains(github.ref, 'refs/tags/s3.url.')
    runs-on: ubuntu-latest
    steps:
      - name: aws login        
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          
      - name: generate s3 presigned URL(valid for 7 days)        
        run: |
          echo "url=$(aws s3 presign s3://coding-test-sample-inputs/sample-large.zip --expires-in 604800)" >> $GITHUB_ENV


      - name: update release with generated url
        uses: jeking3/release-feedback@v1
        with:
         content: |-
            - S3 Presigned URL generated! This download link is valid for 7 days.
            - [Sample-inputs-large]( ${{ env.url }})
         release: ${{ github.event.release.id }}
         token: ${{ secrets.GITHUB_TOKEN }}